[tool.pylint.messages_control]
disable = [
    # Disable too many and too few checks.
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-boolean-expressions",
    "too-many-branches",
    "too-many-function-args",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-nested-blocks",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements",
    "too-few-public-methods",
    # Disable docstrings checks as we don't require excessive documentation.
    "missing-docstring",
    "broad-except",
    "line-too-long",
]

[tool.pylint.format]
max-line-length = {{ cookiecutter.line_length }}
