[tool.ruff]
select = ["F", "E", "W", "I", "D", "UP", "PL"]
ignore = [
  # Pylint
  "PLR0913", # Too many params
  # Pydocstring
  "D211", "D213", # Conflicting rules
  "D417" # Docstring for every param
]
fixable = ["ALL"]
line-length = {{ cookiecutter.line_length }}
target-version = "py{{ cookiecutter.python_version.replace('.', '') }}"

[tool.ruff.format]
exclude = [".git", ".hg", ".mypy_cache", ".tox", ".venv", "_build", "buck-out", "build", "dist", "end", "venv"]

[tool.ruff.per-file-ignores]
"**/*/__init__.py" = ["D104"] # Ignore requiring docstring in empty __init__.py
"tests/*.py" = [
  # Pydocstring
  "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", # Ignore missing docstring
  # Pylint
  "PLR2004", # Magic Values
]
